### ISSUE TITLE
manuscripts showing error

### ISSUE THREAD

**Issue by f2014169** [chaoss/grimoirelab-manuscripts#20]
## when i executed 

manuscripts -d /tmp/reports -u http://localhost:9200 \
   -n GrimoireLab --data-sources git
## Following error was shown

[2018-02-28 05:19:22,352] Debug mode activated
[2018-02-28 05:19:22,353] Generating the report from 2015-01-01 00:00:00+00:00 to 2018-02-27 23:59:59.999999+00:00
[2018-02-28 05:19:22,353] Generating the report data and figs from 2015-01-01 00:00:00+00:00 to 2018-02-27 23:59:59.999999+00:00
[2018-02-28 05:19:22,353] Generating Overview
[2018-02-28 05:19:22,353] CSV file /tmp/reports/data_source_evolution.csv generation in progress
[2018-02-28 05:19:22,355] Metric: 'Commits' (commits); Query: {"size": 0, "aggs": {"1": {"date_histogram": {"time_zone": "UTC", "extended_bounds": {"min": 1420070400000, "max": 1519775999999}, "min_doc_count": 0, "interval": "year", "field": "grimoire_creation_date"}, "aggs": {"2": {"cardinality": {"precision_threshold": 3000, "field": "hash"}}}}}, "query": {"range": {"grimoire_creation_date": {"gte": "2015-01-01T00:00:00+00:00", "lte": "2018-02-27T23:59:59.999999+00:00"}}}, "from": 0}
Traceback (most recent call last):
  File "/usr/local/bin/manuscripts", line 130, in <module>
    report.create()
  File "/usr/local/lib/python3.4/dist-packages/manuscripts/report.py", line 711, in create
    self.create_data_figs()
  File "/usr/local/lib/python3.4/dist-packages/manuscripts/report.py", line 603, in create_data_figs
    self.sections()[section]()
  File "/usr/local/lib/python3.4/dist-packages/manuscripts/report.py", line 267, in sec_overview
    (last, percentage) = m.get_trend()
  File "/usr/local/lib/python3.4/dist-packages/manuscripts/metrics/metrics.py", line 201, in get_trend
    ts = self.get_ts()
  File "/usr/local/lib/python3.4/dist-packages/manuscripts/metrics/metrics.py", line 150, in get_ts
    res = self.get_metrics_data(query)
  File "/usr/local/lib/python3.4/dist-packages/manuscripts/metrics/metrics.py", line 138, in get_metrics_data
    r.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: http://localhost:9200/github_raw/git_enrich/_search

## Any leads ?

**Comment by aswanipranjal** [comment]
@f2014169 checkout #16

**Comment by jgbarah** [comment]
Thanks @aswanipranjal. Yes, the problem is that Manuscripts currently does  not work with Elasticsearch 6.x. @f2014169 please try with Elasticsearch 5.x.

I hope the patch by @aswanipranjal will be accepted soon, which will mean that master HEAD for Manuscripts will also work with Elasticsearch 6.x. And hopefully, that will be incorporated in the next release of the pip packages.

**Comment by jgbarah** [comment]
Duplicate of #16 

Thankis @aswanipranjal for pointing out.

**Comment by aswanipranjal** [comment]
@f2014169 can you check if the issue was resolved at your end? Try pulling the latest changes from the master branch.

**Comment by aswanipranjal** [comment]
@f2014169: the latest version of elasticsearch is 6.2.2. In elasticsearch 6 and above, the Content-Type header has to be mentioned for the request to be valid.

**Comment by f2014169** [comment]
@aswanipranjal  yes it works

**Comment by aswanipranjal** [comment]
@f2014169 great, thanks!

**Comment by jgbarah** [comment]
@aswanipranjal @f2014169 thanks a lot!!
